'use server';

import { revalidatePath } from 'next/cache';

import { getUserRole } from '@/lib/auth/get-user';
import { canDo } from '@/lib/permissions';
import { createServerClient } from '@/lib/supabase/server';
import { createAdminClient } from '@/lib/supabase/admin';
import { pisoSchema, parsePiso } from '@/lib/validators/piso';
import type { Database } from '@/types/database';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AnyClient = any;

type MemberRole = Database['public']['Enums']['member_role'];

export type ActionResult<T = Record<never, never>> =
  | ({ ok: true } & T)
  | { ok: false; error: string };

export type CommunityInviteLink = {
  id: string;
  token: string;
  role: MemberRole;
  expiresAt: string;
  createdAt: string;
};

function siteUrl(): string {
  return process.env.NEXT_PUBLIC_SITE_URL ?? 'http://localhost:3000';
}

// =====================================================================
// generateCommunityInviteLink — creates a new generic invite link
// Invalidates any previous active link for the community.
// =====================================================================
export async function generateCommunityInviteLink(
  communityId: string,
  role: MemberRole = 'propietario',
): Promise<ActionResult<{ link: CommunityInviteLink; joinUrl: string }>> {
  let user;
  let memberRole: MemberRole;
  try {
    ({ user, role: memberRole } = await getUserRole(communityId));
  } catch {
    return { ok: false, error: 'No tienes acceso a esta comunidad' };
  }

  if (!canDo(memberRole, 'member.invite')) {
    return { ok: false, error: 'No tienes permisos para generar enlaces de invitación' };
  }

  const supabase = await createServerClient() as AnyClient;

  // Invalidate existing active links
  await supabase
    .from('community_invite_links')
    .update({ invalidated_at: new Date().toISOString() })
    .eq('community_id', communityId)
    .is('invalidated_at', null);

  // Create new link (token and expires_at generated by DB defaults)
  const { data: link, error } = await supabase
    .from('community_invite_links')
    .insert({
      community_id: communityId,
      role,
      created_by: user.id,
    })
    .select('id, token, role, expires_at, created_at')
    .single();

  if (error || !link) {
    return { ok: false, error: 'No se pudo generar el enlace' };
  }

  revalidatePath(`/c/${communityId}/usuarios`);
  return {
    ok: true,
    link: {
      id: link.id,
      token: link.token,
      role: link.role,
      expiresAt: link.expires_at,
      createdAt: link.created_at,
    },
    joinUrl: `${siteUrl()}/join/${link.token}`,
  };
}

// =====================================================================
// getActiveCommunityInviteLink — returns the current active link or null
// =====================================================================
export async function getActiveCommunityInviteLink(
  communityId: string,
): Promise<ActionResult<{ link: CommunityInviteLink | null; joinUrl: string | null }>> {
  let memberRole: MemberRole;
  try {
    ({ role: memberRole } = await getUserRole(communityId));
  } catch {
    return { ok: false, error: 'No tienes acceso a esta comunidad' };
  }

  if (!canDo(memberRole, 'member.invite')) {
    return { ok: false, error: 'Sin permisos' };
  }

  const supabase = await createServerClient() as AnyClient;

  const { data } = await supabase
    .from('community_invite_links')
    .select('id, token, role, expires_at, created_at')
    .eq('community_id', communityId)
    .is('invalidated_at', null)
    .gt('expires_at', new Date().toISOString())
    .order('created_at', { ascending: false })
    .limit(1)
    .maybeSingle();

  if (!data) {
    return { ok: true, link: null, joinUrl: null };
  }

  return {
    ok: true,
    link: {
      id: data.id,
      token: data.token,
      role: data.role,
      expiresAt: data.expires_at,
      createdAt: data.created_at,
    },
    joinUrl: `${siteUrl()}/join/${data.token}`,
  };
}

// =====================================================================
// invalidateCommunityInviteLink — manually revoke the active link
// =====================================================================
export async function invalidateCommunityInviteLink(
  communityId: string,
): Promise<ActionResult> {
  let memberRole: MemberRole;
  try {
    ({ role: memberRole } = await getUserRole(communityId));
  } catch {
    return { ok: false, error: 'No tienes acceso a esta comunidad' };
  }

  if (!canDo(memberRole, 'member.invite')) {
    return { ok: false, error: 'No tienes permisos' };
  }

  const supabase = await createServerClient() as AnyClient;

  await supabase
    .from('community_invite_links')
    .update({ invalidated_at: new Date().toISOString() })
    .eq('community_id', communityId)
    .is('invalidated_at', null);

  revalidatePath(`/c/${communityId}/usuarios`);
  return { ok: true };
}

// =====================================================================
// acceptCommunityInviteLink — PUBLIC, uses admin client
// Anyone with a valid token can join the community.
// =====================================================================
export async function acceptCommunityInviteLink(
  token: string,
  input: { email: string; fullName: string; phone: string; password: string; piso: string },
): Promise<ActionResult<{ communityId: string; existingUser: boolean }>> {
  // Validate piso format before any DB calls
  const pisoResult = pisoSchema.safeParse(input.piso);
  if (!pisoResult.success) {
    return { ok: false, error: pisoResult.error.errors[0]?.message ?? 'Formato de piso inválido' };
  }
  const { floor, door } = parsePiso(input.piso);

  const admin = createAdminClient() as AnyClient;

  const { data: link } = await admin
    .from('community_invite_links')
    .select('id, community_id, role, expires_at, invalidated_at')
    .eq('token', token)
    .maybeSingle();

  if (!link) {
    return { ok: false, error: 'Enlace no encontrado' };
  }
  if (link.invalidated_at) {
    return { ok: false, error: 'Este enlace ha sido revocado. Solicita uno nuevo al administrador.' };
  }
  if (new Date(link.expires_at) < new Date()) {
    return { ok: false, error: 'Este enlace ha caducado. Solicita uno nuevo al administrador.' };
  }

  const email = input.email.trim().toLowerCase();

  // Check if this user is already a member
  const { data: existingMember } = await admin
    .from('community_members')
    .select('id, profiles!inner(email)')
    .eq('community_id', link.community_id)
    .eq('status', 'active')
    .maybeSingle();

  const alreadyMember = (existingMember?.profiles as unknown as { email: string } | null)?.email === email;
  if (alreadyMember) {
    return { ok: false, error: 'Ya eres miembro de esta comunidad' };
  }

  // Look up unit by floor + door
  const { data: unit } = await admin
    .from('units')
    .select('id')
    .eq('community_id', link.community_id)
    .eq('floor', floor)
    .eq('door', door)
    .eq('type', 'vivienda')
    .maybeSingle();

  if (!unit) {
    return { ok: false, error: `No existe ninguna vivienda en el piso ${input.piso.toUpperCase()} en esta comunidad` };
  }

  // Create or find the auth user
  let userId: string;
  let existingUser = false;

  const { data: createData, error: createError } = await admin.auth.admin.createUser({
    email,
    password: input.password,
    email_confirm: true,
    user_metadata: { full_name: input.fullName },
  });

  if (createError) {
    if (createError.status === 422 || createError.message.toLowerCase().includes('already registered')) {
      existingUser = true;
      const { data: listData } = await admin.auth.admin.listUsers({ page: 1, perPage: 1000 });
      const found = listData?.users.find((u: { email?: string }) => u.email === email);
      if (!found) {
        return { ok: false, error: 'No se pudo identificar el usuario existente' };
      }
      userId = found.id;
    } else {
      return { ok: false, error: 'No se pudo crear la cuenta. Inténtalo de nuevo.' };
    }
  } else {
    userId = createData.user.id;
  }

  // Upsert profile
  await admin.from('profiles').upsert(
    {
      id: userId,
      email,
      full_name: input.fullName,
      phone: input.phone || null,
    },
    { onConflict: 'id' },
  );

  // Insert community membership with unit
  const { error: memberError } = await admin.from('community_members').upsert(
    {
      community_id: link.community_id,
      profile_id: userId,
      unit_id: unit.id,
      role: link.role,
      status: 'active',
      joined_at: new Date().toISOString(),
    },
    { onConflict: 'community_id,profile_id,unit_id' },
  );

  if (memberError) {
    return { ok: false, error: 'No se pudo unir a la comunidad' };
  }

  return { ok: true, communityId: link.community_id, existingUser };
}
